[package]
name = "defluencer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = [] }
cid = "0.8"
either = "1"
futures = { version = "0.3", features = [] }
futures-util= { version = "0.3", features = [] }
heck = { version = "0.4", features = [] }
ipfs-api = { path = "../ipfs-api" }
linked-data = { path = "../linked-data" }
mime_guess = "2.0"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ['full']}
tokio-util = { version = "0.7", features = ["io"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bytes = "1"
web-sys = "0.3"
wasm-bindgen = "0.2"
wasm-streams = "0.2"
#web3 = { version = "0.18", default-features = false, features = ["eip-1193", "wasm"] }