[package]
name = "defluencer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1"
bip39 = "1"
chrono = { version = "0.4", features = [] }
cid = "0.8"
ecdsa = { version = "0.13", features = [] }
ed25519 = { version = "1", features = ["pkcs8"] }
ed25519-dalek = { version = "1", features = [] }
either = "1"
elliptic-curve = { version = "0.11", features = ["serde", "jwk"] }
futures = { version = "0.3", features = [] }
futures-util = { version = "0.3", features = [] }
heck = { version = "0.4", features = [] }
ipfs-api = { path = "../ipfs-api" }
k256 = { version = "0.10", features = ["ecdsa", "keccak256", "jwk"] }
linked-data = { path = "../linked-data" }
mime_guess = "2.0"
multibase = "0.9"
rand_core = { version = "^0.5", features = ["getrandom"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha3 = { version = "0.10", features = [] }
signature = { version = "1", features = [] }
thiserror = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ['full']}
tokio-util = { version = "0.7", features = ["io"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bytes = "1"
web-sys = "0.3"
wasm-bindgen = "0.2"
wasm-streams = "0.2"
web3 = { version = "0.18", default-features = false, features = ["eip-1193", "wasm"] }