[package]
name = "linked-data"
version = "0.1.0"
authors = ["SionoiS <SionoiS@users.noreply.github.com>"]
edition = "2021"
description = "Rust implementation of Defluencer linked data."

[dependencies]
bitvec = { version = "1", default-features = false, features = ["std", "serde"] }
either = { version = "1", default-features = false, features = ["serde"] }
cid = { version = "0.8", default-features = false, features = ["std"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = [] }
serde_with = { version = "1", default-features = false, features = ["macros"] }

[dev-dependencies]
serde_json = "1"